FROM nvidia/cuda:12.9.2-devel-ubuntu24.04

RUN mkdir build 

# build opencv with cuda
WORKDIR /build 

RUN apt update -y && apt install -y wget \
    unzip \
    cmake \
    build-essential \
    libgtk-3-dev \
    libavcodec-dev libavformat-dev libavutil-dev libswscale-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

COPY opencv* .

RUN unzip opencv_contrib*.zip && unzip opencv-*.zip

RUN mv opencv_contrib-4.13.0 ./opencv-4.13.0/ && \
    mkdir build_opencv 

RUN cmake -S ./opencv-4.13.0 -B ./build_opencv \
    -DWITH_GSTREAMER=ON \
    -DWITH_FFMPEG=ON \
    -DWITH_CUDA=ON \
    -DCUDA_ARCH_PTX=12.0 \
    -DCUDA_ARCH_BIN=12.0 \
    -DOPENCV_EXTRA_MODULES_PATH=/build/opencv-4.13.0/opencv_contrib-4.13.0/modules

RUN cd build_opencv && make -j12 install

# install tensorrt
RUN wget https://developer.download.nvidia.com/compute/tensorrt/10.16.1/local_installers/nv-tensorrt-local-repo-ubuntu2404-10.16.1-cuda-12.9_1.0-1_amd64.deb 

RUN dpkg -i nv-tensorrt* && \
    cp /var/nv-tensorrt-local-repo-ubuntu2404-10.16.1-cuda-12.9/*-keyring.gpg /usr/share/keyrings/

RUN apt-get update && \
    apt-get install tensorrt -y

# install dependencies
WORKDIR /

# light 
RUN apt update && apt -y install libeigen3-dev \
    libyaml-cpp-dev \
    libfmt-dev \
    libspdlog-dev \
    libgtest-dev \
    gnupg 

# vpi
RUN apt-key adv --fetch-key https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
RUN apt update && apt -y install software-properties-common
RUN add-apt-repository 'deb https://repo.download.nvidia.com/jetson/x86_64/noble r38.4 main'
RUN apt update && apt -y install libnvvpi4 vpi4-dev vpi4-samples rapidjson-dev

# gstreamer
RUN apt update && apt install -y libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstrtspserver-1.0-dev \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav 

COPY ./native /native

RUN mkdir native_build && \
    cd native_build && \
    cmake ../native && \
    make install

CMD ["sleep", "infinity"]